name: De
on:
  push:
    branches:
      //- main

jobs:
  netflix_project:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout  
        uses: actions/checkout@v4

      # Authenticate with Google Cloud 
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.TEST }}'
      
