name: Netflix-Replica
on:
  push:
    branches:
      - main

jobs:
  netflix_project:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout  
        uses: actions/checkout@v4

      # Authenticate with Google Cloud 
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.TEST_NETFLIX }}'

      # Building Docker image for deidentify only if there are changes
      - name: Checking the path and contents of the file
        run: |
          pwd
          ls
          ll
